### ISSUE TITLE
Update dependencies that are safe

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#22]
I think we can safely update to the newest versions for everything apart from tf, torch and lgbm. Only for pandas there would be a bump in the major version but I am pretty confident it does not break any of our code

**Comment by opcode81** [comment]
Unfortunately, it's not that easy. We definitely only do this as a breaking change (major version change). Just recently, I had an issue where a newer version of sklearn could not load a persisted transformer, so an update of sklearn was not possible without breaking virtually all persisted models.

**Comment by opcode81** [comment]
For the PyPI releases, I have now relaxed the dependencies (see commit fadee277f37d218bb16871f2a25727a4c8b01273). Until incompatibilities arise, let's admit any version that is later than the tested versions as well. This is most convenient for users.

**Comment by MischaPanch** [comment]
> For the PyPI releases, I have now relaxed the dependencies (see commit [fadee27](https://github.com/jambit/sensAI/commit/fadee277f37d218bb16871f2a25727a4c8b01273)). Until incompatibilities arise, let's allow any version that is later than the tested version (in our current requirements.txt). This is most convenient for users.

Cool, thanks! Short question: why did you prefer this post-processing to managing the dependencies directly in requirements.txt?

**Comment by opcode81** [comment]
Because we need to very clearly define the environment we develop/test in for results to be 100% reproducible across machines. The env. we develop in must not depend on the point in time at which we installed it.

Of course, it would be best if we (automatically) tested all of the code in at least two environments:
one which uses the oldest versions we support (i.e. the ones listed in requirements.txt) and one which uses the latest versions of everything.

**Comment by MischaPanch** [comment]
I see. Testing in multiple environments is exactly what tox is good for. I will make a PR soon, also trying to speed up the build
