### ISSUE TITLE
Do not track rst-files in repository

### ISSUE THREAD

**Issue by schroedk** [jambit/sensAI#51]
For the current workflow, one needs to manually update rst-files (using a script build_scripts/update_docu.py). While the script generates rst-files for new modules, it does not delete rst-files for no longer existent modules. So either (hopefully) build breaks on documentation build step or resulting documentation is referencing non-existing code.

@MischaPanch. is there any reason, we track rst-files in the repository and do not generate them on the fly? In a different project, we use a script for exactly this task, which is called in build pipeline, so documentation always reflects actual code base.

**Comment by MischaPanch** [comment]
The reason is that unlike with javadoc etc., the rst files for our sphinx-powered docu are "meant for" manual adjustments, see e.g. how pytorch documentation is built. It is not absolutely necessary, of course, but when I built the script producing them, I wanted to support this, once we actually add more docu. Thus, in order to not accidentally delete manual work done on the rst files, we never delete them in tox invocation but only create the missing ones. If you forget to delete or change a module to a package without updating the rst files, the build fails, so it is quite safe.

I know it is a pain in the ass to keep this in mind when removing/renaming modules but I do think we will want to add more docu to the rst files than just the docstrings eventuallyy. So I would prefer to keep the mechanism as is

**Comment by MischaPanch** [comment]
@schroedk What do you think, can we close this issue?

**Comment by opcode81** [comment]
They may support manual adjustments, but we don't currently make use of it (and perhaps never will). Wouldn't it be more convenient to not track them for now and re-add them if we ever do? Let's do away with this PITA.

**Comment by opcode81** [comment]
The .rst file build has been updated in commit b89097a2ec826baad77228e5b1f08d31d70d1baa to support full auto-generation and the all versioned files have been removed in subsequent commit 71935eb30517fa5c983d50297fe4ae59fb134df6.
